// Zone declarations for carbide-enclave.kubernerdes.com
// Included by /etc/named.conf

zone "carbide-enclave.kubernerdes.com" IN {
    type master;
    file "master/carbide-enclave.kubernerdes.com.zone";
    allow-update { none; };
};

// Reverse zone for 10.0.0.0/24 (infrastructure hosts)
zone "0.0.10.in-addr.arpa" IN {
    type master;
    file "master/10.0.0.rev";
    allow-update { none; };
    notify no;
};
