### RKE2 MANAGEMENT CLUSTER VMs (MACs set in infra/tofu/rke2-cluster/main.tf)

host rancher-01 {
  option host-name "rancher-01";
  hardware ethernet 52:54:00:01:00:01;
  fixed-address 10.0.0.31;
}
host rancher-02 {
  option host-name "rancher-02";
  hardware ethernet 52:54:00:01:00:02;
  fixed-address 10.0.0.32;
}
host rancher-03 {
  option host-name "rancher-03";
  hardware ethernet 52:54:00:01:00:03;
  fixed-address 10.0.0.33;
}

### WORKSTATIONS AND DEVICES

host nuc-01-kvm {
  option host-name "nuc-01-kvm";
  hardware ethernet 48:da:35:6f:72:b3;
  fixed-address 10.0.0.111;
}
host nuc-02-kvm {
  option host-name "nuc-02-kvm";
  hardware ethernet 48:da:35:6f:3e:c2;
  fixed-address 10.0.0.112;
}
host nuc-03-kvm {
  option host-name "nuc-03-kvm";
  hardware ethernet 48:da:35:6f:e4:4f;
  fixed-address 10.0.0.113;
}

host spark-e {
  option host-name "spark-e";
  hardware ethernet 4c:bb:47:2b:e1:94;
  fixed-address 10.0.0.251;
}

